### ISSUE TITLE
org.jacoco:jacoco-maven-plugin:0.8.10:prepare-agent  库不能下载

### ISSUE THREAD

**Issue by qq727127158** [gdut-yy/leetcode-hub-java#2]
* maven有配置阿里云仓库

[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.10:prepare-agent (default) on project leetcode-hub-java: Execution default of goal org.jacoco:jacoco-maven-plugin:0.8.10:prepare-agent failed: A required class was missing while executing org.jacoco:jacoco-maven-plugin:0.8.10:prepare-agent: org/jacoco/core/runtime/AgentOptions
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jacoco:jacoco-maven-plugin:0.8.10
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/wangbowen/.m2/repository/org/jacoco/jacoco-maven-plugin/0.8.10/jacoco-maven-plugin-0.8.10.jar
[ERROR] urls[1] = file:/Users/wangbowen/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar
[ERROR] urls[2] = file:/Users/wangbowen/.m2/repository/org/apache/maven/shared/file-management/1.2.1/file-management-1.2.1.jar
[ERROR] urls[3] = file:/Users/wangbowen/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[4] = file:/Users/wangbowen/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
[ERROR] urls[5] = file:/Users/wangbowen/.m2/repository/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar
[ERROR] urls[6] = file:/Users/wangbowen/.m2/repository/org/jacoco/org.jacoco.core/0.8.10/org.jacoco.core-0.8.10.jar
[ERROR] urls[7] = file:/Users/wangbowen/.m2/repository/org/jacoco/org.jacoco.report/0.8.10/org.jacoco.report-0.8.10.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.jacoco.core.runtime.AgentOptions
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by gdut-yy** [comment]
https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin

@qq727127158 maven 中心仓是有的，如果阿里云仓库拉不到的话，可以试试华为云仓库

```
  <mirrors>
    <mirror>
      <id>huaweicloud</id>
      <mirrorOf>*</mirrorOf>
      <url>https://mirrors.huaweicloud.com/repository/maven/</url>
    </mirror>
  </mirrors>
```
