### ISSUE TITLE
像你学习 , 作者能坚持这么多天

### ISSUE THREAD

**Issue by wuxin0011** [gdut-yy/leetcode-hub-java#3]
最近我也重写了题目仓库 [我的题目](https://github.com/wuxin0011/leetcode)  不知道我能坚持多久  哈哈哈

逛github看到的 要是之前能看到 作者的这个仓库，我也不弄了 但是也不想用maven，感觉太重了 ，于是用原生写了

**Comment by gdut-yy** [comment]
@wuxin0011 互相学习 哈哈哈

构建工具 maven 和 gradle 都是可以的，主要用于锚定 jdk 版本（不同 oj 平台的 jdk 版本存在差异），引入 UT 框架，测试自动化等
